### PR TITLE
Full URL form of PREMIS should be used for rdf:type

### PR DESCRIPTION
**Pull request by mohideen**

### CODE REVIEW

**Comment by awoods** [comment]
What ticket is this PR associated with?

**Comment by escowles** [comment]
FWIW, this change is also included in #3

**Comment by awoods** [comment]
@escowles, does that mean we should close and disregard this PR?

**Comment by mohideen** [comment]
Looking at the rdf:type list of an audit node, I thought it wasn't looking right. May be I'm wrong.
screen shot 2015-04-24 at 9 42 38 am

Also, I missed to update the corresponding test case leading to the Travis failure.

**Comment by escowles** [comment]
@awoods Yes, I think this PR should be closed, since #3 includes the change, and also includes an updated test with the full PREMIS Event URI.

**Pull request closed without merging**
